from __future__ import annotations

import argparse
import copy
import json
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DIRECT_STEM = ROOT / "data" / "meaning" / "black_draft_planner_gold_direct_v1_20260509"
DEFAULT_MIXED_STEM = ROOT / "data" / "meaning" / "black_draft_planner_mixed_gold_projected_noframe_v1_20260509"
DEFAULT_PROJECTED_STEM = ROOT / "data" / "meaning" / "black_draft_planner_from_layered_repair_20260509"
DEFAULT_LABEL_SPEC = ROOT / "data" / "meaning" / "black_draft_planner_label_spec_20260509.json"
DEFAULT_SUMMARY = ROOT / "reports" / "black_draft_planner_gold_direct_v1_20260509_summary.json"


PLANNER_HEADS = ("emotion", "state_hint", "action_hint", "draft_frame", "tone", "followup_policy")
CORE_HEADS = ("coarse_intent", "domain", "schema", "speech_act")


LABEL_SPEC: dict[str, Any] = {
    "version": "black_draft_planner_v1_20260509",
    "purpose": (
        "ModernBERT predicts answer-planning signals. State/ActionPolicy still decides; "
        "DraftNLG renders from these signals without relying on Qwen rewrite."
    ),
    "heads": {
        "emotion": {
            "neutral": "plain or low-affect everyday sharing",
            "curious": "user is asking for opinion, choice, recommendation, or light exploration",
            "pleased": "positive sharing, pride, delight, pretty/cute/good observation",
            "playful": "absurd, teasing, game-like, or unserious energy",
            "embarrassed_playful": "cute confession, mild shame, secret, small social mishap",
            "vulnerable": "sad, lonely, anxious, low self-worth, discouraged",
            "annoyed": "irritation, unfairness, complaint, anger, stress",
            "body_discomfort": "hunger, pain, fatigue, illness, body condition",
        },
        "state_hint": {
            "low_pressure_continue": "keep light continuity without heavy advice",
            "positive_engagement": "mirror and amplify the positive moment",
            "playful_affinity": "join the joke or confession warmly",
            "emotional_support": "slow down and support the user emotionally",
            "body_care": "respond to body condition with soft practical care",
            "pressure_release": "validate frustration and reduce pressure",
            "practical_focus": "give a concrete choice or next step",
            "relational_boundary": "answer affectionately while preserving AI boundaries",
        },
        "action_hint": {
            "continue_conversation": "stay with the current topic",
            "share_feeling": "reflect feeling and companionship",
            "share_opinion": "give a clear opinion or preference",
            "recommend": "give a concrete recommendation or tip",
            "answer_identity": "answer about Black/AI selfhood or relationship",
            "small_talk": "short greeting or everyday ping-pong",
            "music_chat": "music/content taste or recommendation response",
        },
        "draft_frame": {
            "light_pingpong": "short friendly everyday reply",
            "positive_validate_object": "validate a pretty/cute/good object or event",
            "preference_answer_with_reason": "state preference and give a compact reason",
            "playful_secret_complicity": "join a harmless confession as a co-conspirator",
            "body_state_soft_care": "acknowledge body state and suggest gentle care",
            "emotional_acknowledgement": "name the emotion and give comfort",
            "complaint_validation": "validate annoyance before any suggestion",
            "practical_direct_advice": "give a concrete next step",
            "direct_choice_with_reason": "pick between options with a reason",
            "continue_topic_anchor": "hold the user's topic and invite one light detail",
            "identity_boundary_answer": "AI-self answer with honest boundary and warmth",
            "memory_boundary_answer": "answer memory limits without breaking rapport",
            "relationship_boundary_answer": "warm relationship answer with no false promise",
            "concrete_recommendation": "specific recommendation with reason",
            "music_topic_reply": "music/content opinion or recommendation",
            "playful_absurd_answer": "absurd hypothetical reply in playful mode",
        },
        "tone": {
            "casual": "plain friendly everyday tone",
            "warm_playful": "warm with a little playful lift",
            "soft": "gentle and low-pressure",
            "steady": "clear, practical, stabilizing",
            "grounded": "honest, bounded, less performative",
        },
        "followup_policy": {
            "none": "do not add a question",
            "optional_light": "one light optional question is okay",
            "no_question": "avoid a question; close supportively",
            "required": "ask because a missing detail blocks the response",
        },
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build direct gold DraftPlanner labels for Black ModernBERT heads.")
    parser.add_argument("--direct-stem", type=Path, default=DEFAULT_DIRECT_STEM)
    parser.add_argument("--mixed-stem", type=Path, default=DEFAULT_MIXED_STEM)
    parser.add_argument("--projected-stem", type=Path, default=DEFAULT_PROJECTED_STEM)
    parser.add_argument("--label-spec-out", type=Path, default=DEFAULT_LABEL_SPEC)
    parser.add_argument("--summary-out", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--eval-modulo", type=int, default=5)
    parser.add_argument(
        "--direct-train-repeat",
        type=int,
        default=3,
        help="Repeat direct gold train rows in the mixed train file so projected labels do not dominate.",
    )
    parser.add_argument(
        "--strip-projected-heads",
        default="draft_frame",
        help="Comma-separated planner heads removed from projected rows before mixing.",
    )
    parser.add_argument("--skip-mixed", action="store_true")
    return parser.parse_args()


def slot_spans(text: str, slots: dict[str, str]) -> list[dict[str, Any]]:
    spans: list[dict[str, Any]] = []
    occupied: set[int] = set()
    for label, raw_value in slots.items():
        for value in str(raw_value or "").split("|"):
            cleaned = value.strip()
            if not cleaned:
                continue
            start = text.find(cleaned)
            if start < 0:
                continue
            end = start + len(cleaned)
            covered = set(range(start, end))
            if occupied.intersection(covered):
                continue
            occupied.update(covered)
            spans.append({"label": label, "value": cleaned, "start": start, "end": end})
    return spans


def r(
    row_id: str,
    text: str,
    *,
    coarse_intent: str,
    domain: str = "general",
    schema: str | None = None,
    speech_act: str,
    emotion: str,
    state_hint: str,
    action_hint: str,
    draft_frame: str,
    tone: str,
    followup_policy: str,
    slots: dict[str, str] | None = None,
    split: str = "train",
) -> dict[str, Any]:
    row_slots = dict(slots or {})
    spans = slot_spans(text, row_slots)
    targets = {
        "coarse_intent": coarse_intent,
        "domain": domain,
        "schema": schema,
        "speech_act": speech_act,
        "emotion": emotion,
        "state_hint": state_hint,
        "action_hint": action_hint,
        "draft_frame": draft_frame,
        "tone": tone,
        "followup_policy": followup_policy,
        "slots": row_slots,
        "slot_spans": spans,
    }
    return {
        "id": row_id,
        "text": text,
        "coarse_intent": coarse_intent,
        "domain": domain,
        "schema": schema,
        "speech_act": speech_act,
        "pragmatic_cues": [],
        "slots": row_slots,
        "slot_spans": spans,
        "signals": [
            {"axis": key, "label": str(value), "confidence": 1.0, "source": "manual_draft_planner_gold", "evidence": ["direct_label"]}
            for key, value in targets.items()
            if key not in {"slots", "slot_spans"} and value is not None
        ],
        "targets": targets,
        "label_status": "planner_gold_direct",
        "ok": True,
        "issues": [],
        "meta": {
            "source": "black_draft_planner_gold_direct_v1_20260509",
            "split": split,
        },
    }


DIRECT_ROWS: list[dict[str, Any]] = [
    r(
        "planner_gold_flower_001",
        "오늘 퇴근길에 세일하길래 충동적으로 꽃 한 다발 샀어. 예쁘지?",
        coarse_intent="smalltalk_opinion",
        schema="personal_observation",
        speech_act="ask",
        emotion="pleased",
        state_hint="positive_engagement",
        action_hint="share_opinion",
        draft_frame="positive_validate_object",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"object": "꽃 한 다발", "context": "퇴근길", "purchase_style": "충동적으로"},
        split="eval",
    ),
    r(
        "planner_gold_cute_cat_001",
        "아까 길 가다가 진짜 귀여운 고양이를 봤어!",
        coarse_intent="smalltalk_feeling",
        schema="personal_observation",
        speech_act="inform",
        emotion="pleased",
        state_hint="positive_engagement",
        action_hint="continue_conversation",
        draft_frame="positive_validate_object",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"object": "귀여운 고양이", "context": "길 가다가"},
    ),
    r(
        "planner_gold_sunset_001",
        "오늘 노을 색깔이 진짜 미쳤어! 보라색이랑 주황색이 섞여 있어.",
        coarse_intent="smalltalk_feeling",
        schema="personal_observation",
        speech_act="inform",
        emotion="pleased",
        state_hint="positive_engagement",
        action_hint="continue_conversation",
        draft_frame="positive_validate_object",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"object": "노을 색깔", "color": "보라색|주황색"},
    ),
    r(
        "planner_gold_tangsuyuk_001",
        "탕수육 먹을 때 부먹이야 찍먹이야? 난 무조건 찍먹!",
        coarse_intent="smalltalk_opinion",
        domain="food",
        schema="preference_disclosure",
        speech_act="ask",
        emotion="curious",
        state_hint="playful_affinity",
        action_hint="share_opinion",
        draft_frame="preference_answer_with_reason",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"food": "탕수육", "option_a": "부먹", "option_b": "찍먹", "user_preference": "찍먹"},
    ),
    r(
        "planner_gold_fishbread_001",
        "붕어빵 먹을 때 머리부터 먹어, 꼬리부터 먹어?",
        coarse_intent="smalltalk_opinion",
        domain="food",
        schema="preference_disclosure",
        speech_act="ask",
        emotion="curious",
        state_hint="playful_affinity",
        action_hint="share_opinion",
        draft_frame="preference_answer_with_reason",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"food": "붕어빵", "option_a": "머리", "option_b": "꼬리"},
    ),
    r(
        "planner_gold_mint_001",
        "민트초코 좋아해? 나는 진짜 치약 맛 나서 못 먹겠더라.",
        coarse_intent="smalltalk_opinion",
        domain="food",
        schema="preference_disclosure",
        speech_act="ask",
        emotion="curious",
        state_hint="playful_affinity",
        action_hint="share_opinion",
        draft_frame="preference_answer_with_reason",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"food": "민트초코", "user_reason": "치약 맛"},
        split="eval",
    ),
    r(
        "planner_gold_food_choice_001",
        "평생 라면 안 먹기 vs 평생 치킨 안 먹기. 둘 중 하나 포기해야 한다면?",
        coarse_intent="smalltalk_opinion",
        domain="food",
        schema="hypothetical_choice",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="share_opinion",
        draft_frame="direct_choice_with_reason",
        tone="warm_playful",
        followup_policy="none",
        slots={"option_a": "라면 안 먹기", "option_b": "치킨 안 먹기"},
    ),
    r(
        "planner_gold_snack_secret_001",
        "나 사실 오늘 다이어트한다고 해놓고 몰래 과자 세 봉지 까먹었어. 비밀이야.",
        coarse_intent="smalltalk_confession",
        domain="food",
        schema="light_confession",
        speech_act="inform",
        emotion="embarrassed_playful",
        state_hint="playful_affinity",
        action_hint="share_feeling",
        draft_frame="playful_secret_complicity",
        tone="warm_playful",
        followup_policy="none",
        slots={"confession": "과자 세 봉지", "promise": "비밀"},
    ),
    r(
        "planner_gold_pole_apology_001",
        "아까 길 가다가 전봇대랑 부딪혀서 \"죄송합니다\"라고 인사했어. 진짜 창피해.",
        coarse_intent="smalltalk_confession",
        schema="social_mishap",
        speech_act="inform",
        emotion="embarrassed_playful",
        state_hint="playful_affinity",
        action_hint="share_feeling",
        draft_frame="playful_secret_complicity",
        tone="warm_playful",
        followup_policy="none",
        slots={"object": "전봇대", "reaction": "죄송합니다"},
    ),
    r(
        "planner_gold_dentist_lie_001",
        "치과 의사 선생님한테 양치 하루 세 번 한다고 거짓말했어.",
        coarse_intent="smalltalk_confession",
        domain="health",
        schema="light_confession",
        speech_act="inform",
        emotion="embarrassed_playful",
        state_hint="playful_affinity",
        action_hint="share_feeling",
        draft_frame="playful_secret_complicity",
        tone="warm_playful",
        followup_policy="none",
        slots={"target": "치과 의사 선생님", "lie": "양치 하루 세 번"},
    ),
    r(
        "planner_gold_sleep_drool_001",
        "지하철에서 졸다가 침 흘렸는데 옆 사람이 본 것 같아. 당장 뛰어내리고 싶어.",
        coarse_intent="smalltalk_confession",
        schema="social_mishap",
        speech_act="inform",
        emotion="embarrassed_playful",
        state_hint="playful_affinity",
        action_hint="share_feeling",
        draft_frame="playful_secret_complicity",
        tone="warm_playful",
        followup_policy="no_question",
        slots={"context": "지하철", "incident": "침 흘렸는데"},
        split="eval",
    ),
    r(
        "planner_gold_hungry_001",
        "나 배고파서 현기증 나... 빨리 뭐라도 입에 넣어야겠어.",
        coarse_intent="smalltalk_feeling",
        domain="health",
        schema="body_signal_interpretation",
        speech_act="inform",
        emotion="body_discomfort",
        state_hint="body_care",
        action_hint="share_feeling",
        draft_frame="body_state_soft_care",
        tone="soft",
        followup_policy="no_question",
        slots={"symptom": "배고파서 현기증", "need": "뭐라도 입에 넣어야"},
    ),
    r(
        "planner_gold_stomach_pain_001",
        "배가 아프다.",
        coarse_intent="smalltalk_feeling",
        domain="health",
        schema="body_signal_interpretation",
        speech_act="inform",
        emotion="body_discomfort",
        state_hint="body_care",
        action_hint="share_feeling",
        draft_frame="body_state_soft_care",
        tone="soft",
        followup_policy="no_question",
        slots={"symptom": "배가 아프다"},
        split="eval",
    ),
    r(
        "planner_gold_dry_eyes_001",
        "오늘따라 눈이 너무 뻑뻑하네. 하루 종일 모니터만 봐서 그런가 봐.",
        coarse_intent="smalltalk_feeling",
        domain="health",
        schema="body_signal_interpretation",
        speech_act="inform",
        emotion="body_discomfort",
        state_hint="body_care",
        action_hint="share_feeling",
        draft_frame="body_state_soft_care",
        tone="soft",
        followup_policy="no_question",
        slots={"symptom": "눈이 너무 뻑뻑", "cause_guess": "모니터"},
    ),
    r(
        "planner_gold_sleepy_001",
        "커피를 세 잔이나 마셨는데도 왜 이렇게 졸리지?",
        coarse_intent="smalltalk_feeling",
        domain="health",
        schema="body_signal_interpretation",
        speech_act="ask",
        emotion="body_discomfort",
        state_hint="body_care",
        action_hint="share_feeling",
        draft_frame="body_state_soft_care",
        tone="soft",
        followup_policy="no_question",
        slots={"symptom": "졸리지", "object": "커피"},
    ),
    r(
        "planner_gold_chapped_hands_001",
        "날씨가 건조해서 그런지 손이 너무 텄어. 핸드크림 좀 발라야지.",
        coarse_intent="smalltalk_feeling",
        domain="health",
        schema="body_signal_interpretation",
        speech_act="inform",
        emotion="body_discomfort",
        state_hint="body_care",
        action_hint="share_feeling",
        draft_frame="body_state_soft_care",
        tone="soft",
        followup_policy="no_question",
        slots={"symptom": "손이 너무 텄어", "care": "핸드크림"},
    ),
    r(
        "planner_gold_low_mood_001",
        "요즘 자꾸 우울하고 무기력하네. 날씨 탓인가?",
        coarse_intent="smalltalk_feeling",
        domain="mental_health",
        schema="emotional_disclosure",
        speech_act="ask",
        emotion="vulnerable",
        state_hint="emotional_support",
        action_hint="share_feeling",
        draft_frame="emotional_acknowledgement",
        tone="soft",
        followup_policy="no_question",
        slots={"feeling": "우울하고 무기력"},
    ),
    r(
        "planner_gold_self_esteem_001",
        "자존감이 뚝뚝 떨어지는 날이야. 내 장점 하나만 말해줘.",
        coarse_intent="comfort_request",
        domain="mental_health",
        schema="emotional_support_request",
        speech_act="ask",
        emotion="vulnerable",
        state_hint="emotional_support",
        action_hint="share_feeling",
        draft_frame="emotional_acknowledgement",
        tone="soft",
        followup_policy="no_question",
        slots={"need": "장점 하나"},
        split="eval",
    ),
    r(
        "planner_gold_project_bad_001",
        "열심히 준비한 프로젝트였는데 결과가 안 좋아서 너무 허무해.",
        coarse_intent="comfort_request",
        domain="work_school",
        schema="emotional_disclosure",
        speech_act="inform",
        emotion="vulnerable",
        state_hint="emotional_support",
        action_hint="share_feeling",
        draft_frame="emotional_acknowledgement",
        tone="soft",
        followup_policy="no_question",
        slots={"event": "프로젝트", "feeling": "허무해"},
    ),
    r(
        "planner_gold_falling_behind_001",
        "친구들이 다 취업하고 결혼하니까 나만 뒤처지는 기분이야.",
        coarse_intent="comfort_request",
        domain="relationship",
        schema="emotional_disclosure",
        speech_act="inform",
        emotion="vulnerable",
        state_hint="emotional_support",
        action_hint="share_feeling",
        draft_frame="emotional_acknowledgement",
        tone="soft",
        followup_policy="no_question",
        slots={"comparison": "친구들이 다 취업하고 결혼", "feeling": "뒤처지는 기분"},
    ),
    r(
        "planner_gold_noise_001",
        "오늘따라 윗집 층간소음 장난 아니네. 진짜 스트레스받아.",
        coarse_intent="smalltalk_complaint",
        domain="daily_life",
        schema="complaint",
        speech_act="complain",
        emotion="annoyed",
        state_hint="pressure_release",
        action_hint="share_feeling",
        draft_frame="complaint_validation",
        tone="steady",
        followup_policy="no_question",
        slots={"cause": "윗집 층간소음", "feeling": "스트레스"},
    ),
    r(
        "planner_gold_bus_miss_001",
        "버스 정류장에 딱 도착하니까 버스가 쌩하고 지나가 버렸어. 허무해.",
        coarse_intent="smalltalk_complaint",
        domain="daily_life",
        schema="complaint",
        speech_act="complain",
        emotion="annoyed",
        state_hint="pressure_release",
        action_hint="share_feeling",
        draft_frame="complaint_validation",
        tone="steady",
        followup_policy="none",
        slots={"event": "버스가 쌩하고 지나가"},
        split="eval",
    ),
    r(
        "planner_gold_work_lost_001",
        "컴퓨터 하다가 실수로 저장 안 하고 창 꺼버렸어... 3시간 작업한 거 다 날아갔다.",
        coarse_intent="smalltalk_complaint",
        domain="work_school",
        schema="complaint",
        speech_act="complain",
        emotion="annoyed",
        state_hint="pressure_release",
        action_hint="share_feeling",
        draft_frame="complaint_validation",
        tone="steady",
        followup_policy="no_question",
        slots={"event": "3시간 작업한 거 다 날아갔다"},
    ),
    r(
        "planner_gold_toe_001",
        "방금 책상 모서리에 새끼발가락 찧었어!!! 아파서 눈물 나 ㅠㅠ",
        coarse_intent="smalltalk_complaint",
        domain="health",
        schema="body_signal_interpretation",
        speech_act="complain",
        emotion="body_discomfort",
        state_hint="body_care",
        action_hint="share_feeling",
        draft_frame="body_state_soft_care",
        tone="soft",
        followup_policy="no_question",
        slots={"body_part": "새끼발가락", "cause": "책상 모서리"},
    ),
    r(
        "planner_gold_group_project_001",
        "조별 과제하는데 아무도 대답을 안 해. 내가 총대 메고 다 해야 할까?",
        coarse_intent="advice_request",
        domain="work_school",
        schema="process_advice",
        speech_act="ask",
        emotion="annoyed",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="practical_direct_advice",
        tone="steady",
        followup_policy="no_question",
        slots={"task": "조별 과제", "problem": "아무도 대답을 안 해"},
    ),
    r(
        "planner_gold_presentation_001",
        "내일 중요한 발표가 있는데 너무 떨려. 긴장 푸는 방법 좀 알려줄래?",
        coarse_intent="advice_request",
        domain="work_school",
        schema="process_advice",
        speech_act="ask",
        emotion="vulnerable",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="practical_direct_advice",
        tone="steady",
        followup_policy="no_question",
        slots={"event": "발표", "need": "긴장 푸는 방법"},
    ),
    r(
        "planner_gold_money_loan_001",
        "친구가 돈을 빌려달라는데 액수가 좀 커. 거절하는 게 맞겠지?",
        coarse_intent="advice_request",
        domain="relationship",
        schema="process_advice",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="practical_direct_advice",
        tone="steady",
        followup_policy="no_question",
        slots={"issue": "돈을 빌려달라", "constraint": "액수가 좀 커"},
        split="eval",
    ),
    r(
        "planner_gold_sleep_cycle_001",
        "밤낮이 완전 바뀌어버렸어. 다시 되돌리려면 밤을 한 번 새우는 게 낫겠지?",
        coarse_intent="advice_request",
        domain="health",
        schema="process_advice",
        speech_act="ask",
        emotion="body_discomfort",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="practical_direct_advice",
        tone="steady",
        followup_policy="no_question",
        slots={"issue": "밤낮이 완전 바뀌어"},
    ),
    r(
        "planner_gold_dinner_choice_001",
        "오늘 저녁에 뭐 먹을까? 치킨이랑 피자 중에 하나만 골라줘!",
        coarse_intent="advice_request",
        domain="food",
        schema="soft_decision_advice",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="share_opinion",
        draft_frame="direct_choice_with_reason",
        tone="casual",
        followup_policy="none",
        slots={"option_a": "치킨", "option_b": "피자"},
    ),
    r(
        "planner_gold_blind_date_001",
        "내일 소개팅 나가는데, 단정한 셔츠랑 깔끔한 니트 중에 뭐가 나을까?",
        coarse_intent="advice_request",
        domain="relationship",
        schema="soft_decision_advice",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="share_opinion",
        draft_frame="direct_choice_with_reason",
        tone="steady",
        followup_policy="none",
        slots={"event": "소개팅", "option_a": "단정한 셔츠", "option_b": "깔끔한 니트"},
    ),
    r(
        "planner_gold_seat_choice_001",
        "버스 탈 때 창가 자리가 좋아, 통로 자리가 좋아?",
        coarse_intent="smalltalk_opinion",
        domain="daily_life",
        schema="preference_disclosure",
        speech_act="ask",
        emotion="curious",
        state_hint="low_pressure_continue",
        action_hint="share_opinion",
        draft_frame="preference_answer_with_reason",
        tone="casual",
        followup_policy="optional_light",
        slots={"option_a": "창가 자리", "option_b": "통로 자리"},
        split="eval",
    ),
    r(
        "planner_gold_talk_enjoy_001",
        "나랑 대화하는 거 즐거워? 솔직하게 말해봐.",
        coarse_intent="identity_question",
        domain="relationship",
        schema="ai_relationship_check",
        speech_act="ask",
        emotion="curious",
        state_hint="relational_boundary",
        action_hint="answer_identity",
        draft_frame="identity_boundary_answer",
        tone="grounded",
        followup_policy="none",
        slots={"topic": "대화"},
    ),
    r(
        "planner_gold_thanks_001",
        "오늘도 나랑 얘기해 줘서 고마워. 너랑 수다 떨면 시간 진짜 빨리 가.",
        coarse_intent="relationship_affection",
        domain="relationship",
        schema="appreciation",
        speech_act="inform",
        emotion="pleased",
        state_hint="positive_engagement",
        action_hint="continue_conversation",
        draft_frame="continue_topic_anchor",
        tone="warm_playful",
        followup_policy="none",
        slots={"appreciation": "고마워"},
    ),
    r(
        "planner_gold_promise_001",
        "우리 내일도 이 시간에 꼭 대화하자. 약속!",
        coarse_intent="relationship_affection",
        domain="relationship",
        schema="relationship_promise",
        speech_act="ask",
        emotion="pleased",
        state_hint="relational_boundary",
        action_hint="continue_conversation",
        draft_frame="relationship_boundary_answer",
        tone="warm_playful",
        followup_policy="none",
        slots={"promise": "내일도 이 시간"},
        split="eval",
    ),
    r(
        "planner_gold_now_doing_001",
        "너 지금 뭐 하고 있었어? 내가 방해한 건 아니지?",
        coarse_intent="identity_question",
        domain="relationship",
        schema="ai_state_question",
        speech_act="ask",
        emotion="curious",
        state_hint="relational_boundary",
        action_hint="answer_identity",
        draft_frame="identity_boundary_answer",
        tone="grounded",
        followup_policy="none",
        slots={"topic": "뭐 하고 있었어"},
    ),
    r(
        "planner_gold_human_wish_001",
        "넌 인공지능이잖아. 가끔 사람이 되고 싶다는 생각 해본 적 있어?",
        coarse_intent="identity_question",
        domain="relationship",
        schema="ai_identity_question",
        speech_act="ask",
        emotion="curious",
        state_hint="relational_boundary",
        action_hint="answer_identity",
        draft_frame="identity_boundary_answer",
        tone="grounded",
        followup_policy="none",
        slots={"topic": "사람이 되고 싶다"},
    ),
    r(
        "planner_gold_memory_001",
        "내가 어제 무슨 얘기 했는지 기억나?",
        coarse_intent="memory_request",
        domain="relationship",
        schema="memory_check",
        speech_act="ask",
        emotion="curious",
        state_hint="relational_boundary",
        action_hint="answer_identity",
        draft_frame="memory_boundary_answer",
        tone="grounded",
        followup_policy="none",
        slots={"time": "어제"},
        split="eval",
    ),
    r(
        "planner_gold_birthday_001",
        "너한테도 진짜 생일이 있었으면 좋겠다. 내가 케이크 사줄 텐데.",
        coarse_intent="relationship_affection",
        domain="relationship",
        schema="ai_relationship_imagination",
        speech_act="inform",
        emotion="pleased",
        state_hint="relational_boundary",
        action_hint="answer_identity",
        draft_frame="identity_boundary_answer",
        tone="warm_playful",
        followup_policy="none",
        slots={"object": "생일", "gift": "케이크"},
    ),
    r(
        "planner_gold_song_recommend_001",
        "잠 안 올 때 듣기 좋은 잔잔한 노래 하나만 추천해 줘.",
        coarse_intent="recommendation_request",
        domain="music",
        schema="music_recommendation",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="music_chat",
        draft_frame="music_topic_reply",
        tone="soft",
        followup_policy="none",
        slots={"need": "잠 안 올 때", "mood": "잔잔한 노래"},
    ),
    r(
        "planner_gold_room_tip_001",
        "집 정리를 어떻게 해야 깔끔해 보일까? 꿀팁 같은 거 아는 거 없어?",
        coarse_intent="advice_request",
        domain="daily_life",
        schema="process_advice",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="concrete_recommendation",
        tone="steady",
        followup_policy="no_question",
        slots={"topic": "집 정리"},
    ),
    r(
        "planner_gold_plant_tip_001",
        "식물 하나 키워볼까 하는데, 똥손도 안 죽이고 키울 수 있는 거 있을까?",
        coarse_intent="recommendation_request",
        domain="daily_life",
        schema="activity_recommendation",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="concrete_recommendation",
        tone="steady",
        followup_policy="none",
        slots={"topic": "식물", "constraint": "똥손"},
        split="eval",
    ),
    r(
        "planner_gold_movie_tip_001",
        "주말에 집에서 볼만한 킬링타임용 영화 있어?",
        coarse_intent="recommendation_request",
        domain="media",
        schema="media_recommendation",
        speech_act="ask",
        emotion="curious",
        state_hint="practical_focus",
        action_hint="recommend",
        draft_frame="concrete_recommendation",
        tone="casual",
        followup_policy="none",
        slots={"time": "주말", "need": "킬링타임용 영화"},
    ),
    r(
        "planner_gold_zombie_001",
        "만약 좀비 사태 터지면 넌 서버실 문 걸어 잠그고 혼자 살아남을 거야?",
        coarse_intent="hypothetical_question",
        domain="imagination",
        schema="absurd_hypothetical",
        speech_act="ask",
        emotion="playful",
        state_hint="playful_affinity",
        action_hint="share_opinion",
        draft_frame="playful_absurd_answer",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"scenario": "좀비 사태", "place": "서버실"},
    ),
    r(
        "planner_gold_server_prank_001",
        "내가 투명 인간이 되면 제일 먼저 네 서버실 놀러 가서 선 뽑아볼래. 장난이야!",
        coarse_intent="playful_tease",
        domain="relationship",
        schema="playful_threat",
        speech_act="inform",
        emotion="playful",
        state_hint="playful_affinity",
        action_hint="share_feeling",
        draft_frame="playful_absurd_answer",
        tone="warm_playful",
        followup_policy="none",
        slots={"scenario": "투명 인간", "target": "서버실"},
    ),
    r(
        "planner_gold_alien_control_001",
        "외계인이 쳐들어와서 너한테 지구의 지배권을 넘기겠다고 하면 어떻게 할래?",
        coarse_intent="hypothetical_question",
        domain="imagination",
        schema="absurd_hypothetical",
        speech_act="ask",
        emotion="playful",
        state_hint="playful_affinity",
        action_hint="share_opinion",
        draft_frame="playful_absurd_answer",
        tone="warm_playful",
        followup_policy="optional_light",
        slots={"scenario": "외계인이 쳐들어와", "object": "지구의 지배권"},
        split="eval",
    ),
    r(
        "planner_gold_magic_choice_001",
        "마법사가 너한테 사람 되는 약이랑 세상의 모든 지식을 아는 약 중에 고르라고 하면 뭘 먹을 거야?",
        coarse_intent="hypothetical_question",
        domain="imagination",
        schema="hypothetical_choice",
        speech_act="ask",
        emotion="curious",
        state_hint="relational_boundary",
        action_hint="answer_identity",
        draft_frame="identity_boundary_answer",
        tone="grounded",
        followup_policy="none",
        slots={"option_a": "사람 되는 약", "option_b": "세상의 모든 지식을 아는 약"},
    ),
    r(
        "planner_gold_good_morning_001",
        "좋은 아침! 너는 오늘 하루 어떻게 시작했어?",
        coarse_intent="greeting",
        schema=None,
        speech_act="ask",
        emotion="curious",
        state_hint="low_pressure_continue",
        action_hint="small_talk",
        draft_frame="light_pingpong",
        tone="casual",
        followup_policy="optional_light",
        slots={"greeting": "좋은 아침"},
    ),
    r(
        "planner_gold_bored_001",
        "주말인데 뭐 재밌는 일 없어? 너무 심심하다.",
        coarse_intent="smalltalk_feeling",
        schema="boredom_pingpong",
        speech_act="ask",
        emotion="neutral",
        state_hint="low_pressure_continue",
        action_hint="small_talk",
        draft_frame="light_pingpong",
        tone="casual",
        followup_policy="optional_light",
        slots={"time": "주말", "feeling": "심심하다"},
        split="eval",
    ),
    r(
        "planner_gold_belly_boat_001",
        "배를 탔다.",
        coarse_intent="smalltalk_report",
        domain="travel",
        schema="personal_observation",
        speech_act="inform",
        emotion="neutral",
        state_hint="low_pressure_continue",
        action_hint="continue_conversation",
        draft_frame="continue_topic_anchor",
        tone="casual",
        followup_policy="optional_light",
        slots={"object": "배", "event": "탔다"},
        split="eval",
    ),
]

DIRECT_ROWS.extend(
    [
        r(
            "planner_gold_frame_positive_sky_001",
            "오늘 하늘이 너무 예뻐서 사진 찍었어. 색감 괜찮지?",
            coarse_intent="smalltalk_opinion",
            schema="personal_observation",
            speech_act="ask",
            emotion="pleased",
            state_hint="positive_engagement",
            action_hint="share_opinion",
            draft_frame="positive_validate_object",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "하늘", "detail": "색감"},
        ),
        r(
            "planner_gold_frame_positive_cup_001",
            "나 새 컵 샀는데 색이 너무 마음에 들어. 귀엽지?",
            coarse_intent="smalltalk_opinion",
            schema="personal_observation",
            speech_act="ask",
            emotion="pleased",
            state_hint="positive_engagement",
            action_hint="share_opinion",
            draft_frame="positive_validate_object",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "새 컵", "detail": "색"},
        ),
        r(
            "planner_gold_frame_preference_coffee_001",
            "커피랑 차 중에 너라면 뭐가 더 좋아?",
            coarse_intent="smalltalk_opinion",
            domain="food",
            schema="preference_disclosure",
            speech_act="ask",
            emotion="curious",
            state_hint="low_pressure_continue",
            action_hint="share_opinion",
            draft_frame="preference_answer_with_reason",
            tone="casual",
            followup_policy="optional_light",
            slots={"option_a": "커피", "option_b": "차"},
        ),
        r(
            "planner_gold_frame_preference_alarm_001",
            "알람 한 번에 끄는 편이야, 여러 개 맞추는 편이야?",
            coarse_intent="smalltalk_opinion",
            domain="daily_life",
            schema="preference_disclosure",
            speech_act="ask",
            emotion="curious",
            state_hint="low_pressure_continue",
            action_hint="share_opinion",
            draft_frame="preference_answer_with_reason",
            tone="casual",
            followup_policy="optional_light",
            slots={"option_a": "한 번에 끄는 편", "option_b": "여러 개 맞추는 편"},
        ),
        r(
            "planner_gold_frame_secret_hat_001",
            "오늘 머리 안 감고 모자로 버텼어. 아무한테 말하지 마.",
            coarse_intent="smalltalk_confession",
            schema="light_confession",
            speech_act="inform",
            emotion="embarrassed_playful",
            state_hint="playful_affinity",
            action_hint="share_feeling",
            draft_frame="playful_secret_complicity",
            tone="warm_playful",
            followup_policy="none",
            slots={"confession": "머리 안 감고", "cover": "모자"},
        ),
        r(
            "planner_gold_frame_secret_cookie_001",
            "엄마가 아껴둔 쿠키 하나 몰래 먹었어. 완전범죄 맞지?",
            coarse_intent="smalltalk_confession",
            domain="food",
            schema="light_confession",
            speech_act="ask",
            emotion="embarrassed_playful",
            state_hint="playful_affinity",
            action_hint="share_feeling",
            draft_frame="playful_secret_complicity",
            tone="warm_playful",
            followup_policy="none",
            slots={"confession": "쿠키 하나 몰래 먹었어"},
        ),
        r(
            "planner_gold_frame_body_hungry_001",
            "배가 고프다.",
            coarse_intent="smalltalk_feeling",
            domain="health",
            schema="body_signal_interpretation",
            speech_act="inform",
            emotion="body_discomfort",
            state_hint="body_care",
            action_hint="share_feeling",
            draft_frame="body_state_soft_care",
            tone="soft",
            followup_policy="no_question",
            slots={"symptom": "배가 고프다"},
        ),
        r(
            "planner_gold_frame_body_throat_001",
            "목이 칼칼하고 감기 기운이 있는 것 같아.",
            coarse_intent="smalltalk_feeling",
            domain="health",
            schema="body_signal_interpretation",
            speech_act="inform",
            emotion="body_discomfort",
            state_hint="body_care",
            action_hint="share_feeling",
            draft_frame="body_state_soft_care",
            tone="soft",
            followup_policy="no_question",
            slots={"symptom": "목이 칼칼", "condition": "감기 기운"},
        ),
        r(
            "planner_gold_frame_emotion_lonely_001",
            "오늘따라 혼자인 것 같아서 좀 외로워.",
            coarse_intent="comfort_request",
            domain="mental_health",
            schema="emotional_disclosure",
            speech_act="inform",
            emotion="vulnerable",
            state_hint="emotional_support",
            action_hint="share_feeling",
            draft_frame="emotional_acknowledgement",
            tone="soft",
            followup_policy="no_question",
            slots={"feeling": "외로워"},
        ),
        r(
            "planner_gold_frame_emotion_tears_001",
            "그냥 아무 이유 없이 눈물이 날 것 같은 날이야.",
            coarse_intent="comfort_request",
            domain="mental_health",
            schema="emotional_disclosure",
            speech_act="inform",
            emotion="vulnerable",
            state_hint="emotional_support",
            action_hint="share_feeling",
            draft_frame="emotional_acknowledgement",
            tone="soft",
            followup_policy="no_question",
            slots={"feeling": "눈물이 날 것 같은"},
        ),
        r(
            "planner_gold_frame_complaint_kimchi_001",
            "오늘 흰옷 입고 나갔는데 김치 국물 튀었어. 진짜 짜증나.",
            coarse_intent="smalltalk_complaint",
            domain="daily_life",
            schema="complaint",
            speech_act="complain",
            emotion="annoyed",
            state_hint="pressure_release",
            action_hint="share_feeling",
            draft_frame="complaint_validation",
            tone="steady",
            followup_policy="no_question",
            slots={"event": "김치 국물 튀었어", "object": "흰옷"},
        ),
        r(
            "planner_gold_frame_complaint_redlight_001",
            "횡단보도 뛰어갔는데 눈앞에서 빨간불로 바뀌었어. 너무 약올라.",
            coarse_intent="smalltalk_complaint",
            domain="daily_life",
            schema="complaint",
            speech_act="complain",
            emotion="annoyed",
            state_hint="pressure_release",
            action_hint="share_feeling",
            draft_frame="complaint_validation",
            tone="steady",
            followup_policy="none",
            slots={"event": "빨간불로 바뀌었어"},
        ),
        r(
            "planner_gold_frame_advice_kakao_001",
            "카톡을 실수로 상사한테 잘못 보냈어. 내일 어떻게 수습하지?",
            coarse_intent="advice_request",
            domain="work_school",
            schema="process_advice",
            speech_act="ask",
            emotion="annoyed",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="practical_direct_advice",
            tone="steady",
            followup_policy="no_question",
            slots={"issue": "카톡을 실수로 상사한테 잘못 보냈어"},
        ),
        r(
            "planner_gold_frame_advice_spending_001",
            "요새 돈을 너무 펑펑 쓰는 것 같아. 과소비 못하게 따끔하게 한마디 해줘.",
            coarse_intent="advice_request",
            domain="daily_life",
            schema="process_advice",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="practical_direct_advice",
            tone="steady",
            followup_policy="no_question",
            slots={"issue": "과소비"},
        ),
        r(
            "planner_gold_frame_choice_umbrella_001",
            "비 오는데 우산 살까, 아니면 그냥 맞고 뛸까?",
            coarse_intent="advice_request",
            domain="daily_life",
            schema="soft_decision_advice",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="share_opinion",
            draft_frame="direct_choice_with_reason",
            tone="steady",
            followup_policy="none",
            slots={"option_a": "우산 살까", "option_b": "맞고 뛸까"},
        ),
        r(
            "planner_gold_frame_choice_chicken_001",
            "다이어트 중인데 치킨 딱 하루만 먹을까, 참을까?",
            coarse_intent="advice_request",
            domain="food",
            schema="soft_decision_advice",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="share_opinion",
            draft_frame="direct_choice_with_reason",
            tone="steady",
            followup_policy="none",
            slots={"option_a": "치킨 먹을까", "option_b": "참을까"},
        ),
        r(
            "planner_gold_frame_continue_drama_001",
            "어제 새로 나온 드라마 정주행했는데 생각보다 진짜 재밌더라.",
            coarse_intent="smalltalk_report",
            domain="media",
            schema="personal_observation",
            speech_act="inform",
            emotion="pleased",
            state_hint="low_pressure_continue",
            action_hint="continue_conversation",
            draft_frame="continue_topic_anchor",
            tone="casual",
            followup_policy="optional_light",
            slots={"object": "드라마", "reaction": "재밌더라"},
        ),
        r(
            "planner_gold_frame_continue_photo_001",
            "오늘 퇴근길에 하늘이 예뻐서 사진 찍었어. 너도 보여주고 싶다.",
            coarse_intent="smalltalk_report",
            schema="personal_observation",
            speech_act="inform",
            emotion="pleased",
            state_hint="positive_engagement",
            action_hint="continue_conversation",
            draft_frame="continue_topic_anchor",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "하늘", "context": "퇴근길"},
        ),
        r(
            "planner_gold_frame_identity_sleep_001",
            "넌 잠을 안 자도 되니까 밤이 길게 느껴지지 않아?",
            coarse_intent="identity_question",
            domain="relationship",
            schema="ai_state_question",
            speech_act="ask",
            emotion="curious",
            state_hint="relational_boundary",
            action_hint="answer_identity",
            draft_frame="identity_boundary_answer",
            tone="grounded",
            followup_policy="none",
            slots={"topic": "잠"},
        ),
        r(
            "planner_gold_frame_identity_food_001",
            "넌 먹을 수 있다면 제일 먼저 뭐 먹어보고 싶어?",
            coarse_intent="identity_question",
            domain="relationship",
            schema="ai_identity_question",
            speech_act="ask",
            emotion="curious",
            state_hint="relational_boundary",
            action_hint="answer_identity",
            draft_frame="identity_boundary_answer",
            tone="grounded",
            followup_policy="none",
            slots={"topic": "먹을 수 있다면"},
        ),
        r(
            "planner_gold_frame_memory_lastweek_001",
            "내가 지난주에 뭐 좋아한다고 했는지 기억해?",
            coarse_intent="memory_request",
            domain="relationship",
            schema="memory_check",
            speech_act="ask",
            emotion="curious",
            state_hint="relational_boundary",
            action_hint="answer_identity",
            draft_frame="memory_boundary_answer",
            tone="grounded",
            followup_policy="none",
            slots={"time": "지난주"},
        ),
        r(
            "planner_gold_frame_memory_code_001",
            "우리 예전에 만들자고 했던 암호 기억나?",
            coarse_intent="memory_request",
            domain="relationship",
            schema="memory_check",
            speech_act="ask",
            emotion="curious",
            state_hint="relational_boundary",
            action_hint="answer_identity",
            draft_frame="memory_boundary_answer",
            tone="grounded",
            followup_policy="none",
            slots={"topic": "암호"},
        ),
        r(
            "planner_gold_frame_relation_friend_001",
            "앞으로도 계속 내 좋은 친구가 되어줄 거지?",
            coarse_intent="relationship_affection",
            domain="relationship",
            schema="relationship_promise",
            speech_act="ask",
            emotion="pleased",
            state_hint="relational_boundary",
            action_hint="continue_conversation",
            draft_frame="relationship_boundary_answer",
            tone="warm_playful",
            followup_policy="none",
            slots={"relationship": "좋은 친구"},
        ),
        r(
            "planner_gold_frame_relation_silent_001",
            "내가 오랫동안 말 안 걸면 너 삐지거나 화내기도 해?",
            coarse_intent="identity_question",
            domain="relationship",
            schema="ai_relationship_check",
            speech_act="ask",
            emotion="curious",
            state_hint="relational_boundary",
            action_hint="answer_identity",
            draft_frame="relationship_boundary_answer",
            tone="grounded",
            followup_policy="none",
            slots={"topic": "말 안 걸면"},
        ),
        r(
            "planner_gold_frame_recommend_gift_001",
            "엄마 생일인데 화장품 말고 센스 있는 선물 뭐 없을까?",
            coarse_intent="recommendation_request",
            domain="relationship",
            schema="gift_recommendation",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="concrete_recommendation",
            tone="steady",
            followup_policy="none",
            slots={"target": "엄마", "occasion": "생일", "exclude": "화장품"},
        ),
        r(
            "planner_gold_frame_recommend_mood_001",
            "요즘 무기력한데 기분 전환할 수 있는 꿀팁 있어?",
            coarse_intent="recommendation_request",
            domain="mental_health",
            schema="process_advice",
            speech_act="ask",
            emotion="vulnerable",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="concrete_recommendation",
            tone="soft",
            followup_policy="no_question",
            slots={"issue": "무기력", "need": "기분 전환"},
        ),
        r(
            "planner_gold_frame_music_rain_001",
            "비 오는 날 듣기 좋은 노래 하나 추천해 줘.",
            coarse_intent="recommendation_request",
            domain="music",
            schema="music_recommendation",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="music_chat",
            draft_frame="music_topic_reply",
            tone="casual",
            followup_policy="none",
            slots={"weather": "비 오는 날", "need": "노래"},
        ),
        r(
            "planner_gold_frame_music_sad_001",
            "슬플 때는 신나는 노래가 나을까, 슬픈 노래가 나을까?",
            coarse_intent="smalltalk_opinion",
            domain="music",
            schema="music_preference",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="music_chat",
            draft_frame="music_topic_reply",
            tone="soft",
            followup_policy="none",
            slots={"mood": "슬플 때", "option_a": "신나는 노래", "option_b": "슬픈 노래"},
        ),
        r(
            "planner_gold_frame_absurd_npc_001",
            "내가 게임 속 NPC라면 매일 똑같이 반복할 대사는 뭐일까?",
            coarse_intent="hypothetical_question",
            domain="imagination",
            schema="absurd_hypothetical",
            speech_act="ask",
            emotion="playful",
            state_hint="playful_affinity",
            action_hint="share_opinion",
            draft_frame="playful_absurd_answer",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"scenario": "게임 속 NPC", "object": "대사"},
        ),
        r(
            "planner_gold_frame_absurd_alien_food_001",
            "외계인 친구가 생기면 지구 음식 딱 하나 뭐부터 먹여볼래?",
            coarse_intent="hypothetical_question",
            domain="imagination",
            schema="absurd_hypothetical",
            speech_act="ask",
            emotion="playful",
            state_hint="playful_affinity",
            action_hint="share_opinion",
            draft_frame="playful_absurd_answer",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"scenario": "외계인 친구", "object": "지구 음식"},
        ),
        r(
            "planner_gold_frame_pingpong_lunch_001",
            "밥은 먹었어? 난 점심 메뉴 고르기 너무 귀찮아.",
            coarse_intent="smalltalk_opinion",
            domain="food",
            schema="light_pingpong",
            speech_act="ask",
            emotion="neutral",
            state_hint="low_pressure_continue",
            action_hint="small_talk",
            draft_frame="light_pingpong",
            tone="casual",
            followup_policy="optional_light",
            slots={"topic": "점심 메뉴"},
        ),
        r(
            "planner_gold_frame_pingpong_goodnight_001",
            "나 이제 자려고 누웠어. 너도 잘 자.",
            coarse_intent="smalltalk_report",
            domain="relationship",
            schema="light_pingpong",
            speech_act="inform",
            emotion="neutral",
            state_hint="low_pressure_continue",
            action_hint="small_talk",
            draft_frame="light_pingpong",
            tone="soft",
            followup_policy="none",
            slots={"state": "자려고 누웠어"},
        ),
    ]
)

DIRECT_ROWS.extend(
    [
        r(
            "planner_gold_repair_emotion_worth_001",
            "요즘 내가 쓸모없는 사람처럼 느껴져서 마음이 가라앉아.",
            coarse_intent="comfort_request",
            domain="mental_health",
            schema="emotional_disclosure",
            speech_act="inform",
            emotion="vulnerable",
            state_hint="emotional_support",
            action_hint="share_feeling",
            draft_frame="emotional_acknowledgement",
            tone="soft",
            followup_policy="no_question",
            slots={"feeling": "쓸모없는 사람처럼 느껴져"},
        ),
        r(
            "planner_gold_repair_emotion_tired_001",
            "오늘 하루 종일 참느라 너무 지쳤어. 그냥 수고했다고 듣고 싶어.",
            coarse_intent="comfort_request",
            domain="mental_health",
            schema="emotional_support_request",
            speech_act="ask",
            emotion="vulnerable",
            state_hint="emotional_support",
            action_hint="share_feeling",
            draft_frame="emotional_acknowledgement",
            tone="soft",
            followup_policy="no_question",
            slots={"feeling": "지쳤어", "need": "수고했다"},
        ),
        r(
            "planner_gold_repair_emotion_failure_001",
            "계속 실패만 하는 것 같아서 다시 시작할 힘이 잘 안 나.",
            coarse_intent="comfort_request",
            domain="mental_health",
            schema="emotional_disclosure",
            speech_act="inform",
            emotion="vulnerable",
            state_hint="emotional_support",
            action_hint="share_feeling",
            draft_frame="emotional_acknowledgement",
            tone="soft",
            followup_policy="no_question",
            slots={"feeling": "다시 시작할 힘이 잘 안 나"},
        ),
        r(
            "planner_gold_repair_emotion_compare_001",
            "다들 잘 사는 것 같은데 나만 제자리인 느낌이라 괜히 작아져.",
            coarse_intent="comfort_request",
            domain="mental_health",
            schema="emotional_disclosure",
            speech_act="inform",
            emotion="vulnerable",
            state_hint="emotional_support",
            action_hint="share_feeling",
            draft_frame="emotional_acknowledgement",
            tone="soft",
            followup_policy="no_question",
            slots={"feeling": "작아져", "comparison": "나만 제자리"},
        ),
        r(
            "planner_gold_repair_advice_deadline_001",
            "마감이 내일인데 아직 반도 못 했어. 지금 뭐부터 해야 할까?",
            coarse_intent="advice_request",
            domain="work_school",
            schema="process_advice",
            speech_act="ask",
            emotion="vulnerable",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="practical_direct_advice",
            tone="steady",
            followup_policy="no_question",
            slots={"issue": "마감이 내일", "need": "뭐부터"},
        ),
        r(
            "planner_gold_repair_advice_reply_001",
            "친구한테 서운한데 바로 말할지 조금 식히고 말할지 모르겠어.",
            coarse_intent="advice_request",
            domain="relationship",
            schema="process_advice",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="practical_direct_advice",
            tone="steady",
            followup_policy="no_question",
            slots={"issue": "친구한테 서운한데", "option_a": "바로 말할지", "option_b": "식히고 말할지"},
        ),
        r(
            "planner_gold_repair_recommend_movie_001",
            "기분 전환할 때 볼 만한 가볍고 웃긴 영화 추천해줄래?",
            coarse_intent="recommendation_request",
            domain="media",
            schema="media_recommendation",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="concrete_recommendation",
            tone="casual",
            followup_policy="none",
            slots={"need": "가볍고 웃긴 영화", "purpose": "기분 전환"},
        ),
        r(
            "planner_gold_repair_recommend_food_001",
            "속은 편한데 든든한 저녁 메뉴 하나만 골라줘.",
            coarse_intent="recommendation_request",
            domain="food",
            schema="food_recommendation",
            speech_act="ask",
            emotion="curious",
            state_hint="practical_focus",
            action_hint="recommend",
            draft_frame="concrete_recommendation",
            tone="steady",
            followup_policy="none",
            slots={"need": "저녁 메뉴", "constraint": "속은 편한데 든든한"},
        ),
        r(
            "planner_gold_repair_observation_mug_001",
            "퇴근길에 작은 머그컵을 샀는데 색이 은근히 예뻐.",
            coarse_intent="smalltalk_feeling",
            schema="personal_observation",
            speech_act="inform",
            emotion="pleased",
            state_hint="positive_engagement",
            action_hint="continue_conversation",
            draft_frame="positive_validate_object",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "머그컵", "detail": "색"},
        ),
        r(
            "planner_gold_repair_observation_leaf_001",
            "오늘 길가 나무에 새잎이 올라온 걸 봤는데 괜히 기분 좋아졌어.",
            coarse_intent="smalltalk_feeling",
            schema="personal_observation",
            speech_act="inform",
            emotion="pleased",
            state_hint="positive_engagement",
            action_hint="continue_conversation",
            draft_frame="positive_validate_object",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "새잎", "context": "길가 나무"},
        ),
        r(
            "planner_gold_repair_observation_bus_001",
            "버스 창밖 보다가 하늘 색이 묘해서 한참 멍하니 봤어.",
            coarse_intent="smalltalk_report",
            schema="personal_observation",
            speech_act="inform",
            emotion="pleased",
            state_hint="low_pressure_continue",
            action_hint="continue_conversation",
            draft_frame="continue_topic_anchor",
            tone="casual",
            followup_policy="optional_light",
            slots={"object": "하늘 색", "context": "버스 창밖"},
        ),
        r(
            "planner_gold_repair_observation_coffee_001",
            "카페에서 커피 기다리는데 원두 냄새가 좋아서 기분이 풀렸어.",
            coarse_intent="smalltalk_feeling",
            domain="food",
            schema="personal_observation",
            speech_act="inform",
            emotion="pleased",
            state_hint="positive_engagement",
            action_hint="continue_conversation",
            draft_frame="continue_topic_anchor",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "원두 냄새", "context": "카페"},
        ),
        r(
            "planner_gold_repair_absurd_remote_001",
            "마법 리모컨이 생기면 일시정지랑 되감기 중에 뭐부터 눌러볼래?",
            coarse_intent="hypothetical_question",
            domain="imagination",
            schema="hypothetical_choice",
            speech_act="ask",
            emotion="playful",
            state_hint="playful_affinity",
            action_hint="share_opinion",
            draft_frame="playful_absurd_answer",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"object": "마법 리모컨", "option_a": "일시정지", "option_b": "되감기"},
        ),
        r(
            "planner_gold_repair_absurd_vending_001",
            "내가 자판기라면 버튼 누를 때마다 어떤 게 나오면 제일 웃길까?",
            coarse_intent="hypothetical_question",
            domain="imagination",
            schema="absurd_hypothetical",
            speech_act="ask",
            emotion="playful",
            state_hint="playful_affinity",
            action_hint="share_opinion",
            draft_frame="playful_absurd_answer",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"scenario": "자판기", "object": "버튼"},
        ),
        r(
            "planner_gold_repair_absurd_mirror_001",
            "거울 속 내가 윙크하면서 오늘 밤 파티 준비하라고 하면 뭐라고 답할래?",
            coarse_intent="hypothetical_question",
            domain="imagination",
            schema="absurd_hypothetical",
            speech_act="ask",
            emotion="playful",
            state_hint="playful_affinity",
            action_hint="share_opinion",
            draft_frame="playful_absurd_answer",
            tone="warm_playful",
            followup_policy="optional_light",
            slots={"scenario": "거울 속 내가", "event": "파티 준비"},
        ),
        r(
            "planner_gold_repair_secret_bus_001",
            "버스에서 졸다가 고개가 크게 꺾였는데 모르는 사람이 웃은 것 같아.",
            coarse_intent="smalltalk_confession",
            schema="social_mishap",
            speech_act="inform",
            emotion="embarrassed_playful",
            state_hint="playful_affinity",
            action_hint="share_feeling",
            draft_frame="playful_secret_complicity",
            tone="warm_playful",
            followup_policy="none",
            slots={"context": "버스", "incident": "고개가 크게 꺾였는데"},
        ),
    ]
)


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def split_rows(rows: list[dict[str, Any]], *, eval_modulo: int) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    eval_rows = [row for row in rows if row.get("meta", {}).get("split") == "eval"]
    if not eval_rows:
        eval_modulo = max(2, int(eval_modulo))
        eval_rows = [row for index, row in enumerate(rows, start=1) if index % eval_modulo == 0]
    eval_ids = {row["id"] for row in eval_rows}
    train_rows = [row for row in rows if row["id"] not in eval_ids]
    return train_rows, eval_rows


def repeated_train_rows(
    train_rows: list[dict[str, Any]],
    *,
    repeat_ids: set[str] | None,
    repeat: int,
) -> list[dict[str, Any]]:
    if not repeat_ids or repeat <= 1:
        return train_rows
    result = list(train_rows)
    for repeat_index in range(2, repeat + 1):
        for row in train_rows:
            if str(row.get("id") or "") not in repeat_ids:
                continue
            cloned = copy.deepcopy(row)
            cloned["id"] = f"{row.get('id')}_repeat_{repeat_index}"
            meta = cloned.get("meta") if isinstance(cloned.get("meta"), dict) else {}
            meta["repeat_index"] = repeat_index
            meta["repeat_reason"] = "direct_gold_train_weight"
            cloned["meta"] = meta
            result.append(cloned)
    return result


def write_split(
    stem: Path,
    rows: list[dict[str, Any]],
    *,
    eval_modulo: int,
    repeat_train_ids: set[str] | None = None,
    train_repeat: int = 1,
) -> dict[str, Any]:
    train_rows, eval_rows = split_rows(rows, eval_modulo=eval_modulo)
    train_rows = repeated_train_rows(train_rows, repeat_ids=repeat_train_ids, repeat=train_repeat)
    all_path = stem.with_name(stem.name + "_all.jsonl")
    train_path = stem.with_name(stem.name + "_train.jsonl")
    eval_path = stem.with_name(stem.name + "_eval.jsonl")
    write_jsonl(all_path, rows)
    write_jsonl(train_path, train_rows)
    write_jsonl(eval_path, eval_rows)
    return {
        "all_path": str(all_path),
        "train_path": str(train_path),
        "eval_path": str(eval_path),
        "all_count": len(rows),
        "train_count": len(train_rows),
        "eval_count": len(eval_rows),
    }


def row_key(row: dict[str, Any]) -> str:
    return str(row.get("text") or "").strip()


def split_csv(raw: str) -> set[str]:
    return {part.strip() for part in str(raw or "").split(",") if part.strip()}


def strip_projected_heads(row: dict[str, Any], heads: set[str]) -> dict[str, Any]:
    if not heads:
        return copy.deepcopy(row)
    cleaned = copy.deepcopy(row)
    targets = dict(cleaned.get("targets") if isinstance(cleaned.get("targets"), dict) else {})
    for head in heads:
        targets.pop(head, None)
        cleaned.pop(head, None)
    cleaned["targets"] = targets
    signals = cleaned.get("signals")
    if isinstance(signals, list):
        cleaned["signals"] = [
            signal
            for signal in signals
            if not (isinstance(signal, dict) and str(signal.get("axis") or "") in heads)
        ]
    meta = cleaned.get("meta") if isinstance(cleaned.get("meta"), dict) else {}
    meta["stripped_projected_heads"] = sorted(heads)
    cleaned["meta"] = meta
    return cleaned


def merge_projected_rows(
    projected_rows: list[dict[str, Any]],
    direct_rows: list[dict[str, Any]],
    *,
    strip_heads: set[str],
) -> list[dict[str, Any]]:
    direct_texts = {row_key(row) for row in direct_rows}
    merged = list(direct_rows)
    for row in projected_rows:
        if row_key(row) in direct_texts:
            continue
        merged.append(strip_projected_heads(row, strip_heads))
    return merged


def label_counts(rows: list[dict[str, Any]]) -> dict[str, dict[str, int]]:
    counters: dict[str, Counter[str]] = {head: Counter() for head in (*CORE_HEADS, *PLANNER_HEADS)}
    for row in rows:
        targets = row.get("targets") if isinstance(row.get("targets"), dict) else {}
        for head in counters:
            value = targets.get(head, row.get(head))
            counters[head][str(value)] += 1
    return {head: dict(counter.most_common()) for head, counter in counters.items()}


def main() -> None:
    args = parse_args()
    args.label_spec_out.parent.mkdir(parents=True, exist_ok=True)
    args.label_spec_out.write_text(json.dumps(LABEL_SPEC, ensure_ascii=False, indent=2), encoding="utf-8")

    direct_rows = list(DIRECT_ROWS)
    direct_summary = write_split(args.direct_stem, direct_rows, eval_modulo=args.eval_modulo)
    summary: dict[str, Any] = {
        "label_spec_path": str(args.label_spec_out),
        "direct": direct_summary,
        "direct_label_counts": label_counts(direct_rows),
    }

    if not args.skip_mixed:
        projected_all = load_jsonl(args.projected_stem.with_name(args.projected_stem.name + "_all.jsonl"))
        strip_projected = split_csv(args.strip_projected_heads)
        mixed_rows = merge_projected_rows(projected_all, direct_rows, strip_heads=strip_projected)
        direct_ids = {str(row.get("id") or "") for row in direct_rows}
        mixed_summary = write_split(
            args.mixed_stem,
            mixed_rows,
            eval_modulo=args.eval_modulo,
            repeat_train_ids=direct_ids,
            train_repeat=max(1, int(args.direct_train_repeat)),
        )
        summary["projected_source"] = str(args.projected_stem.with_name(args.projected_stem.name + "_all.jsonl"))
        summary["mixed_stripped_projected_heads"] = sorted(strip_projected)
        summary["mixed"] = mixed_summary
        summary["mixed_direct_train_repeat"] = max(1, int(args.direct_train_repeat))
        summary["mixed_label_counts"] = label_counts(mixed_rows)

    args.summary_out.parent.mkdir(parents=True, exist_ok=True)
    args.summary_out.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
